stages:
   - build
   - test
   
# build pipeline  
build container:
  stage: build
  script:
    - apt-get update && apt-get install -y r-base
    - Rscript trainingScript.R
    - echo model trained successfully
  tags:
    - docker

# test pipeline  
test container:
  stage: test
  script:
    - apt-get update && apt-get install -y r-base
    - Rscript scoringScript.R
    - echo model scored successfully
  tags:
    - docker
