stages:
   - build
   
# build pipeline  
build container:
  stage: build
  script:
    - apt-get update && apt-get install -y r-base
    - Rscript sample_script.R
    - echo container built successfully
  tags:
    - docker
